### PR TITLE
.gitignore added

### PR DESCRIPTION
**Pull request by arnon001**
Hey Guzio I made a .gitignore, and its working

### CODE REVIEW

**Comment by GuzioMG** [comment]
Why'd `.md` files be ignored?

**Comment by arnon001** [comment]
Actually I Dont Really Know, But I Guess Since its a Not Really needed file

**Comment by GuzioMG** [comment]
It's not needed for Java, that's right, but it's needed for GitHub (README.md). And ignoring it would make it so that when the repo is cloned, that file would be ignored. That would make it impossible to edit this file locally and limit users to the GitHub editor.

**Comment by arnon001** [comment]
ok, fixing it

**Comment by GuzioMG** [comment]
OK, merged. Also, why doesn't crrl+c work in the merging editor? So stupid...

**Pull request merged**
